# Generated by Django 5.1.3 on 2024-12-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=100)),
                ('fechalanzamiento', models.DateField()),
                ('plataforma', models.CharField(max_length=100)),
            ],
        ),
    ]
